### ISSUE TITLE
Database Query

### ISSUE THREAD

**Issue by williamnwogbo** [arietimmerman/laravel-url-shortener#3]
CREATE TABLE `mycm`.`art_urls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(1000) NULL,
  `url` TEXT NULL,
  `reference` TEXT NULL,
  `meta` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE);

**Comment by arietimmerman** [comment]
Not sure what the issue is here.
