### ISSUE TITLE
Migration successful but not applied

### ISSUE THREAD

**Issue by eli-cquoin** [arietimmerman/laravel-url-shortener#4]
I installed it as instructed but the tables are not added in my database.

`composer require arietimmerman/laravel-url-shortener`

When I run `php artisan migrate`, I got the following:

`Migrating: 2017_11_30_000000_create_urls_table
Migrated:  2017_11_30_000000_create_urls_table (0.27 seconds)`

I also did `php artisan url:shorten http://www.example.com` and I got `Shortened to: http://localhost/___LLy`

I checked my database and it's not there. What could be missing?

**Comment by arietimmerman** [comment]
Are you sure you have one `.env` file and looking in the correct database?
