### ISSUE TITLE
URL redirect not working since changing app url

### ISSUE THREAD

**Issue by supportskins** [arietimmerman/laravel-url-shortener#7]
Hi,
I change my Laravel app url from http to https (both in .env and using .htaccess). I use your package to create short URL for login forms for different client companies, something like

```
http://www.appurl.com/login/company/slug  -> http://www.appurl.com/~CODE
```
while the url

```
http://www.appurl.com/login/
```

is the backend URL

Now since I changed the app URL to https the redirect does not work

http://www.appurl.com/~CODE now leads to https://www.appurl.com/login/ instead of https://www.appurl.com/login/company/slug

however https://www.appurl.com/~CODE correctly leads to https://www.appurl.com/login/company/slug

I have updated the database values in the art_urls table to point them to the correct URL. It is a weird issue which I cannot seem to fix it. I have cleared cache, routes and config. But it still does not work. Please help.

**Comment by arietimmerman** [comment]
This does not sound like an issue with this package. Have you already managed to solve it?

**Comment by supportskins** [comment]
Yes it was not a package issue rather an issue with the server htaccess mod_rewrite causing this weird behaviour.

Thanks for the follow up.
